export default [
  {
    status: "5",
    firstName: "",
    middleName: "",
    lastName: "",
    IDNumber: "",
    gender: "",
    dateOfBirth: "",
    oINumber: "",
    haveBirthCertificate: "",
    clientType: "",
  },
  {
    maritalStatus: "",
    orphanStatus: "",
    onArvs: "",
    onCotrimoxazole: "",
    artRegimen: "",
    dateStartedTreatment: "",
    disablityType: "",
    disability: "",
    education: "",
    educationLevel: "",
    reasonForNotReachingOLevel: "",
  },
  {
    address: "",
    primaryClinic: "",
    supportGroup: "",
    mobileNumber: "",
    mobileOwner: "",
    ownerName: "",
    mobileOwnerRelation: "",
    secondaryMobileNumber: "",
    ownSecondaryMobile: "",
    secondaryMobileOwnerName: "",
    secondaryMobileownerRelation: "",
  },
  {
    isKeypopulation: "",
    keyPopulation: "",
    hivStatusKnown: "",
    dateTested: "",
    disclosureType: "",
    hIVDisclosureLocation: "",
    transmissionMode: "",
    consentToMHealth: "",
    dateJoined: "",
  },
  {
    selfPrimaryCareGiver: "",
    relationship: "",
    pfirstName: "",
    plastName: "",
    pmobileNumber: "",
    pgender: "",
    referer: "",
    refererName: "",
  },
];
